
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jan 17 22:33:16 CET 2011
//----------------------------------------------------

package de.cgawron.go.sgf;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int Open = 2;
  public static final int Value = 6;
  public static final int error = 1;
  public static final int Close = 3;
  public static final int Property = 5;
  public static final int Semi = 4;
  public static final int EOF = 0;
}

