
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 27 16:56:55 CET 2010
//----------------------------------------------------

package de.cgawron.go.sgf;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int Open = 2;
  public static final int Value = 6;
  public static final int error = 1;
  public static final int Close = 3;
  public static final int Property = 5;
  public static final int Semi = 4;
  public static final int EOF = 0;
}

